// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9W2EXC4xLaWmffu54edrF18TF5qtsyk',
    appId: '1:1028882347189:web:0c6c5bdd0ea43edf127afc',
    messagingSenderId: '1028882347189',
    projectId: 'rtdata-56733',
    authDomain: 'rtdata-56733.firebaseapp.com',
    storageBucket: 'rtdata-56733.appspot.com',
    measurementId: 'G-DMTLVH1VRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgKw9wZHAhjtha72_6GzIqjjxLxzGkQMc',
    appId: '1:1028882347189:android:aab1866bcb4bbe47127afc',
    messagingSenderId: '1028882347189',
    projectId: 'rtdata-56733',
    storageBucket: 'rtdata-56733.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN9W2EXC4xLaWmffu54edrF18TF5qtsyk',
    appId: '1:1028882347189:web:b54b98aa0bafaaee127afc',
    messagingSenderId: '1028882347189',
    projectId: 'rtdata-56733',
    authDomain: 'rtdata-56733.firebaseapp.com',
    storageBucket: 'rtdata-56733.appspot.com',
    measurementId: 'G-QDVH8VKD4W',
  );
}
